// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anumypiphyebzquhveby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFudW15cGlwaHllYnpxdWh2ZWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDg3NTAsImV4cCI6MjA1OTkyNDc1MH0.J0fWNthRMSH5D08nZFa9i9h9bAU55qkSYU4l0qLovTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);